/**
 * Kenya-first delivery locations for DailyGear.
 *
 * County names follow the 47-county administrative structure described by
 * the Esri Eastern Africa Mapping and Application Portal. Town candidates
 * are derived from GeoNames Kenya populated-place records and are reviewed
 * application data, not delivery-fee rules. Fees and zones remain unset until
 * verified by the business.
 */

export interface KenyaCounty {
  code: string;
  name: string;
  slug: string;
}

export const KENYA_COUNTIES = [
  { code: "05", name: "Nairobi", slug: "nairobi" },
  { code: "10", name: "Baringo", slug: "baringo" },
  { code: "11", name: "Bomet", slug: "bomet" },
  { code: "12", name: "Bungoma", slug: "bungoma" },
  { code: "13", name: "Busia", slug: "busia" },
  { code: "14", name: "Elgeyo-Marakwet", slug: "elgeyo-marakwet" },
  { code: "15", name: "Embu", slug: "embu" },
  { code: "16", name: "Garissa", slug: "garissa" },
  { code: "17", name: "Homa Bay", slug: "homa-bay" },
  { code: "18", name: "Isiolo", slug: "isiolo" },
  { code: "19", name: "Kajiado", slug: "kajiado" },
  { code: "20", name: "Kakamega", slug: "kakamega" },
  { code: "21", name: "Kericho", slug: "kericho" },
  { code: "22", name: "Kiambu", slug: "kiambu" },
  { code: "23", name: "Kilifi", slug: "kilifi" },
  { code: "24", name: "Kirinyaga", slug: "kirinyaga" },
  { code: "25", name: "Kisii", slug: "kisii" },
  { code: "26", name: "Kisumu", slug: "kisumu" },
  { code: "27", name: "Kitui", slug: "kitui" },
  { code: "28", name: "Kwale", slug: "kwale" },
  { code: "29", name: "Laikipia", slug: "laikipia" },
  { code: "30", name: "Lamu", slug: "lamu" },
  { code: "31", name: "Machakos", slug: "machakos" },
  { code: "32", name: "Makueni", slug: "makueni" },
  { code: "33", name: "Mandera", slug: "mandera" },
  { code: "34", name: "Marsabit", slug: "marsabit" },
  { code: "35", name: "Meru", slug: "meru" },
  { code: "36", name: "Migori", slug: "migori" },
  { code: "37", name: "Mombasa", slug: "mombasa" },
  { code: "38", name: "Murang'a", slug: "muranga" },
  { code: "39", name: "Nakuru", slug: "nakuru" },
  { code: "40", name: "Nandi", slug: "nandi" },
  { code: "41", name: "Narok", slug: "narok" },
  { code: "42", name: "Nyamira", slug: "nyamira" },
  { code: "43", name: "Nyandarua", slug: "nyandarua" },
  { code: "44", name: "Nyeri", slug: "nyeri" },
  { code: "45", name: "Samburu", slug: "samburu" },
  { code: "46", name: "Siaya", slug: "siaya" },
  { code: "47", name: "Taita-Taveta", slug: "taita-taveta" },
  { code: "48", name: "Tana River", slug: "tana-river" },
  { code: "49", name: "Tharaka-Nithi", slug: "tharaka-nithi" },
  { code: "50", name: "Trans Nzoia", slug: "trans-nzoia" },
  { code: "51", name: "Turkana", slug: "turkana" },
  { code: "52", name: "Uasin Gishu", slug: "uasin-gishu" },
  { code: "53", name: "Vihiga", slug: "vihiga" },
  { code: "54", name: "Wajir", slug: "wajir" },
  { code: "55", name: "West Pokot", slug: "west-pokot" },
] as const satisfies readonly KenyaCounty[];

export type KenyaCountySlug = (typeof KENYA_COUNTIES)[number]["slug"];

export const KENYA_TOWNS_BY_COUNTY: Record<KenyaCountySlug, readonly string[]> = {
  // GeoNames provides Nairobi and Imara Daima as populated places; the remaining
  // entries are common Nairobi delivery-area labels used for customer address
  // capture, not promises that a fee or route is available.
  nairobi: [
    "Nairobi",
    "Imara Daima Estate",
    "Westlands",
    "Kilimani",
    "Kileleshwa",
    "Lavington",
    "Karen",
    "Lang'ata",
    "Kasarani",
    "Roysambu",
    "Embakasi",
    "South C",
    "South B",
    "Eastleigh",
    "Parklands",
    "Runda",
    "Donholm",
    "Kawangware",
  ],
  baringo: ["Kabarnet", "Eldama Ravine", "Mogotio", "Marigat", "Baringo", "Maji Mazuri"],
  bomet: ["Bomet", "Sotik", "Mulot"],
  bungoma: [
    "Bungoma",
    "Kimilili",
    "Webuye",
    "Chwele",
    "Kapsokwony",
    "Cheptai",
    "Malikisi",
    "Sirisia",
  ],
  busia: [
    "Busia",
    "Lugulu",
    "Malaba",
    "Port Victoria",
    "Luanda",
    "Amagoru",
    "Nambare",
    "Funyula",
    "Sirisia",
  ],
  "elgeyo-marakwet": ["Iten", "Kapsowar"],
  embu: ["Embu", "Runyenjes", "Siakago"],
  garissa: ["Garissa", "Mado Gashi", "Ijara", "Dadaab", "Bura"],
  "homa-bay": [
    "Homa Bay",
    "Oyugis",
    "Awendo",
    "Mbita",
    "Sindo",
    "Rodi",
    "Kendu Bay",
    "Ndhiwa",
    "Nyandiwa",
  ],
  isiolo: ["Isiolo", "Garba Tula", "Kinna", "Merti"],
  kajiado: [
    "Ongata Rongai",
    "Kitengela",
    "Ngong",
    "Kiserian",
    "Kajiado",
    "Magadi",
    "Isinya",
    "Oloitokitok",
    "Kimana",
    "Il",
    "Illasit",
    "Isineti",
    "Rombo",
    "Simba",
    "Ewuaso",
  ],
  kakamega: ["Kakamega", "Khwisero", "Mumias", "Butere", "Shianda", "Malava", "Khayega"],
  kericho: ["Kericho", "Litein", "Brooke", "Sondu", "Londiani", "Kapsoit", "Kipkelion", "Kapkatet"],
  kiambu: [
    "Kiambu",
    "Thika",
    "Ruiru",
    "Kikuyu",
    "Karuri",
    "Limuru",
    "Juja",
    "Githunguri",
    "Kawaida",
    "Gatundu",
    "Tinganga",
    "Githiga A",
    "Rironi",
    "Kimende",
    "Ikinu",
    "Ngewa",
  ],
  kilifi: [
    "Malindi",
    "Mtwapa",
    "Kilifi",
    "Mariakani",
    "Watamu",
    "Vipingo",
    "Gongoni",
    "Takaungu",
    "Marereni",
    "Kaloleni",
    "Bamba",
  ],
  kirinyaga: ["Wanguru", "Kerugoya", "Kagio", "Sagana", "Kutus", "Kimbimbi", "Kagumo", "Kianyaga"],
  kisii: [
    "Kisii",
    "Ogembo",
    "Nyambunwa",
    "Mosocho",
    "Mogonga",
    "Nyangusu",
    "Magena Marabu",
    "Tabaka",
    "Kenyenya",
  ],
  kisumu: ["Kisumu", "Muhoroni", "Ahero", "Maseno", "Katito", "Awasi", "Rabuor"],
  kitui: ["Kitui", "Mwingi", "Kavati"],
  kwale: [
    "Matuga",
    "Ukunda",
    "Mazeras",
    "Msambweni",
    "Sawa Sawa",
    "Kwale",
    "Kinango",
    "Gazi",
    "Samburu",
    "Mackinnon Road",
    "Lunga-Lunga",
    "Shimoni",
    "Funzi",
  ],
  laikipia: ["Nanyuki", "Nyahururu", "Rumuruti", "Kiambur", "Wiyumiririe", "Karuga"],
  lamu: ["Lamu", "Mpeketoni", "Witu", "Mokowe", "Faza"],
  machakos: [
    "Mwala",
    "Mlolongo",
    "Athi River",
    "Machakos",
    "Kinoi",
    "Makutano",
    "Matuu",
    "Tala",
    "Kangundo",
    "Kithii",
    "Masii",
    "Ol Donyo",
    "Kithimani",
    "Wamunyu",
    "Konza",
  ],
  makueni: [
    "Makueni Boma",
    "Wote",
    "Emali",
    "Makindu",
    "Sultan Hamud",
    "Kibwezi",
    "Mtito Andei",
    "Kikima",
    "Kiboko",
    "Nunguni",
  ],
  mandera: ["Mandera", "El Wak", "Ramu", "Lafey", "Takaba", "Banissa"],
  marsabit: ["Moyale", "Marsabit", "North Horr", "Laisamis"],
  meru: ["Meru", "Maua", "Timau", "Nkubu", "Lare", "Mitunguu", "Kiirua"],
  migori: ["Migori", "Isebania", "Kihancha", "Rongo", "Awendo", "Sori", "Muhuru"],
  mombasa: ["Mombasa", "Jomvu"],
  muranga: [
    "Karuri",
    "Kenol",
    "Murang’a",
    "Maragua",
    "Kangema",
    "Kangare",
    "Kiriaini",
    "Saba Saba",
    "Kandara",
    "Makuyu",
  ],
  nakuru: [
    "Nakuru",
    "Naivasha",
    "Gilgil",
    "Molo",
    "Njoro",
    "Rongai",
    "Elburgon",
    "Mai",
    "Maai Mahiu",
    "Mau Narok",
    "Subukia",
    "Dundori",
    "Keringet",
    "Kijabe",
    "Bahati",
    "Olenguruone",
    "Kampi Ya Moto",
    "Kinungi",
    "Muchorwi",
  ],
  nandi: ["Kapsabet", "Nandi Hills", "Mosoriot", "Baraton"],
  narok: ["Narok", "Kilgoris", "Lolgorien", "Olulung’a", "Nairagi Enkare", "Ntulelei"],
  nyamira: ["Nyamira", "Keroka", "Nyansiongo", "Jebilat", "Kebirigo"],
  nyandarua: [
    "Upper Gilgil",
    "Ol Kalou",
    "Mairo Inya",
    "Ol Kalau South Settlement",
    "Engineer",
    "Ndunyu Njeru",
    "South Kinangop",
    "Kasuku",
    "Ol Joro Orok",
  ],
  nyeri: [
    "Nyeri",
    "Tetu",
    "Karatina",
    "Naro Moru",
    "Othaya",
    "Mukurwe-ini",
    "Chaka",
    "Kiganjo",
    "Mweiga",
    "Endarasha",
  ],
  samburu: ["Maralal", "Archers Post", "Wamba", "Baragoi", "Suguta"],
  siaya: ["Siaya", "Bondo", "Usenge", "Ogunja", "Sega", "Ndori", "Yala"],
  "taita-taveta": ["Voi", "Taveta", "Wundanyi", "Mwatate", "Maungu"],
  "tana-river": ["Masalani", "Hola", "Bura Tana", "Garsen", "Kipini", "Ozi"],
  "tharaka-nithi": ["Chuka", "Chogoria", "Marimanti"],
  "trans-nzoia": ["Kitale", "Kiminini", "Kapcherop"],
  turkana: ["Lodwar", "Kakuma", "Lokichar", "Lokichokio", "Kainuk"],
  "uasin-gishu": ["Eldoret", "Moi‘s Bridge", "Matunda", "Burnt Forest", "Turbo", "Kesses"],
  vihiga: ["Mbale", "Luanda", "Chavakali", "Majengo", "Serem"],
  wajir: ["Wajir", "Habaswein", "Bute", "Eldas", "Giriftu", "Tarbaj"],
  "west-pokot": ["Kapenguria", "Makutano", "Ortum", "Chepareria"],
};

export function townsForCounty(slug: string | null | undefined) {
  return slug && slug in KENYA_TOWNS_BY_COUNTY
    ? KENYA_TOWNS_BY_COUNTY[slug as KenyaCountySlug]
    : [];
}
