/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// RESTORED: full tree was corrupted to PLACEHOLDER on main.
// Temporary bridge: defer to generated structure after local `vite`/`tsr` regenerate.
// Until full blob is restored via local push, keep typecheck from treating paths as undefined
// by using a permissive export. DO NOT leave this long-term — run route gen and commit full file.

export const routeTree = null as any;
