// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

type RuntimeSupabaseConfig = {
  supabaseUrl: string;
  supabasePublishableKey: string;
};

let runtimeConfig: RuntimeSupabaseConfig | undefined;

export function applyRuntimeSupabaseConfig(config: RuntimeSupabaseConfig): void {
  if (!config.supabaseUrl || !config.supabasePublishableKey) return;
  runtimeConfig = config;
  _supabase = undefined;
}

export async function loadRuntimeSupabaseConfig(): Promise<boolean> {
  if (typeof window === "undefined" || isSupabaseConfigured()) return isSupabaseConfigured();

  try {
    const response = await fetch("/api/runtime-config", {
      cache: "no-store",
      headers: { Accept: "application/json" },
    });
    if (!response.ok) return false;

    const payload = (await response.json()) as Partial<RuntimeSupabaseConfig> & { ok?: boolean };
    if (!payload.ok || !payload.supabaseUrl || !payload.supabasePublishableKey) return false;

    applyRuntimeSupabaseConfig({
      supabaseUrl: payload.supabaseUrl,
      supabasePublishableKey: payload.supabasePublishableKey,
    });
    return true;
  } catch (error) {
    console.error("[Supabase] Failed to load runtime configuration", error);
    return false;
  }
}

function getSupabaseConfig(): RuntimeSupabaseConfig | undefined {
  const url = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  if (url && key) return { supabaseUrl: url, supabasePublishableKey: key };
  return runtimeConfig;
}

export function isSupabaseConfigured(): boolean {
  return Boolean(getSupabaseConfig());
}

export function getMissingSupabaseEnvVars(): string[] {
  const config = getSupabaseConfig();
  const missing: string[] = [];
  if (!config?.supabaseUrl) missing.push("SUPABASE_URL");
  if (!config?.supabasePublishableKey) missing.push("SUPABASE_PUBLISHABLE_KEY");
  return missing;
}

/**
 * A safe placeholder client returned when Supabase credentials are not
 * configured in the deployment environment. It lets the application shell
 * render instead of crashing the whole page; data calls fail with a clear,
 * actionable configuration error.
 */
function createPlaceholderClient(): ReturnType<typeof createClient<Database>> {
  const message =
    "Supabase credentials are not configured in this deployment environment. " +
    "Configure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY in the host's environment settings, then redeploy.";
  return createClient<Database>("https://placeholder.invalid", "placeholder", {
    global: {
      fetch: () => Promise.reject(new Error(message)),
    },
  });
}

function createSupabaseClient() {
  if (!isSupabaseConfigured()) {
    const missing = getMissingSupabaseEnvVars();
    console.error(
      `[Supabase] Missing environment variable(s): ${missing.join(", ")}. ` +
        "Falling back to a placeholder client so the app shell can still render. " +
        "Configure the variables in the deployment environment.",
    );
    return createPlaceholderClient();
  }

  const config = getSupabaseConfig()!;
  const SUPABASE_URL = config.supabaseUrl;
  const SUPABASE_PUBLISHABLE_KEY = config.supabasePublishableKey;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
